//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.Persistence.Scripts.Workers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgresWorkerElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgresWorkerElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Common.Persistence.Scripts.Workers.PostgresWorkerElement", typeof(PostgresWorkerElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO WORKERS VALUES(@name, @surname, @patronymic, @email, @is_staff, @is_candidate, @id_company) RETURNING id as &quot;Id&quot;, name as &quot;Name&quot;, surname as &quot;Surname&quot;, patronymic as &quot;Patronymic&quot;, email as &quot;Email&quot;, is_staff as &quot;IsStaff&quot;, is_candidate as &quot;IsCandidate&quot;, company_id as &quot;CompanyId&quot;.
        /// </summary>
        internal static string AddWorker {
            get {
                return ResourceManager.GetString("AddWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DeleteWorkerById {
            get {
                return ResourceManager.GetString("DeleteWorkerById", resourceCulture);
            }
        }
        
        internal static string GetUnitWorkers {
            get {
                return ResourceManager.GetString("GetUnitWorkers", resourceCulture);
            }
        }
        
        internal static string GetWorkerByEmail {
            get {
                return ResourceManager.GetString("GetWorkerByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetCompanyWorkers {
            get {
                return ResourceManager.GetString("GetCompanyWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id as &quot;Id&quot;, name as &quot;Name&quot;, surname as &quot;Surname&quot;, patronymic as &quot;Patronymic&quot;, email as &quot;Email&quot;, is_staff as &quot;IsStaff&quot;, is_candidate as &quot;IsCandidate&quot;, company_id as &quot;CompanyId&quot; FROM WORKERS WHERE id=@worker_id.
        /// </summary>
        internal static string GetWorkerById {
            get {
                return ResourceManager.GetString("GetWorkerById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UpdateWorker {
            get {
                return ResourceManager.GetString("UpdateWorker", resourceCulture);
            }
        }
    }
}
