//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Common.Persistence.Scripts.Companies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgresCompanyElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgresCompanyElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Common.Persistence.Scripts.Companies.PostgresCompanyElement", typeof(PostgresCompanyElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO COMPANIES(name, description, director_id) VALUES(@name, @description, @director_id) RETURNING id as &quot;Id&quot;, name as &quot;Name&quot;, description as &quot;Description&quot;, image_id as &quot;ImageId&quot;, director_id as &quot;DirectorId&quot;.
        /// </summary>
        internal static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO companies_users VALUES(@company_id, @user_id).
        /// </summary>
        internal static string AddRecruiterToCompany {
            get {
                return ResourceManager.GetString("AddRecruiterToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM COMPANIES WHERE id = @id.
        /// </summary>
        internal static string DeleteCompanyById {
            get {
                return ResourceManager.GetString("DeleteCompanyById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE companies_users where company_id=@company_id AND recruiterId=@recruiter_id.
        /// </summary>
        internal static string DeleteRecruiterById {
            get {
                return ResourceManager.GetString("DeleteRecruiterById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT company_id as &quot;CompanyId&quot;, user_id as &quot;UserId&quot; FROM companies_users where company_id=@company_id and user_id=@user_id.
        /// </summary>
        internal static string GetCompaniesUsersByIds {
            get {
                return ResourceManager.GetString("GetCompaniesUsersByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id as &quot;id&quot;, image_id as &quot;ImageId&quot;, name as &quot;Name&quot;, description as &quot;Description&quot;, director_id as &quot;DirectorId&quot; FROM COMPANIES WHERE id = @id.
        /// </summary>
        internal static string GetCompanyById {
            get {
                return ResourceManager.GetString("GetCompanyById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetUserCompanies {
            get {
                return ResourceManager.GetString("GetUserCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE COMPANIES SET name = @name, description = @description, image_id=@image_id where id = @id RETURNING id as &quot;Id&quot;, name As &quot;Name&quot;, description as &quot;Description&quot;, image_id as &quot;ImageId&quot;, director_id as &quot;DirectorId&quot;.
        /// </summary>
        internal static string UpdateCompany {
            get {
                return ResourceManager.GetString("UpdateCompany", resourceCulture);
            }
        }
    }
}
